config/routes.rb
      match 'copy' => 'copy_projects#copy', via: :post
      put :modules
      put :archive
      put :unarchive
      patch :types

      get 'column_sums', controller: 'work_packages'

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info, as: 'confirm_destroy'
    end

    resource :enumerations, controller: 'project_enumerations', only: [:update, :destroy]

    resources :versions, only: [:new, :create] do
      collection do
        put :close_completed
      end
    end

    # this is only another name for versions#index
    # For nice "road in the url for the index action
    # this could probably be rewritten with a resource :as => 'roadmap'
    match '/roadmap' => 'versions#index', via: :get

    resources :news, only: [:index, :new, :create]

    namespace :time_entries do
      resource :report, controller: 'reports', only: [:show]
    end
    resources :time_entries, controller: 'timelog'

    resources :wiki, except: [:index, :new, :create] do
      collection do
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/diff/:version/vs/:version_from' => 'wiki#diff', as: 'wiki_diff_compare'
        get '/diff(/:version)' => 'wiki#diff', as: 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', as: 'wiki_annotate'
        match :rename, via: [:get, :patch]
        get :parent_page, action: 'edit_parent_page'
        patch :parent_page, action: 'update_parent_page'
        get :history
        post :protect
        post :add_attachment
        get :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
        post :preview
      end
    end
    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => 'wiki#show'

    namespace :work_packages do
      resources :calendar, controller: 'calendars', only: [:index]
    end

    resources :work_packages, only: [:new, :create] do
      get :new_type, on: :collection

      collection do
        match '/report/:detail' => 'work_packages/reports#report_details', via: :get
        match '/report' => 'work_packages/reports#report', via: :get
      end

      # states managed by client-side routing on work_package#index
      get '/*state' => 'work_packages#index', on: :member, id: /\d+/

      # explicitly define index for preserving the order in which
      # the path helpers are created - this otherwise leads to
      # link_to { controller: ... } to point to the create_new path
      get '/' => 'work_packages#index', on: :collection
      get '/create_new' => 'work_packages#index', on: :collection
    end

    resources :activity, :activities, only: :index, controller: 'activities'

    resources :boards do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, except: [:index, :show], shallow: true

    resources :members, only: [:create, :update, :destroy], shallow: true do
      match :autocomplete_for_member, on: :collection, via: [:get, :post]
    end

    resource :repository, controller: 'repositories', except: [:new] do
      get :edit # needed as show is configured manually with a wildcard

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info
      get :committers
      post :committers
      get :graph
      get :revisions

      get '/statistics', action: :stats, as: 'stats'

      get '(/revisions/:rev)/diff.:format', action: :diff
      get '(/revisions/:rev)/diff(/*path)', action: :diff,
                                            format: false

      get '(/revisions/:rev)/:format/*path', action: :entry,
                                             format: /raw/,
                                             rev: /[a-z0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*path)", format: false,
                                                   action: action,
                                                   rev: /[a-z0-9\.\-_]+/
      end

      get '/revision(/:rev)', rev: /[a-z0-9\.\-_]+/,
                              action: :revision,
                              as: 'show_revision'

      get '(/revisions/:rev)(/*path)', action: :show,
                                       format: false,
                                       rev: /[a-z0-9\.\-_]+/
    end
  end

  get '/admin' => 'admin#index'

  # TODO: evaluate whether this can be turned into a namespace
  scope 'admin' do
    match '/projects' => 'admin#projects', via: :get

    resources :enumerations

    resources :groups do
      member do
        get :autocomplete_for_user
        # this should be put into it's own resource
        match '/members' => 'groups#add_users', via: :post, as: 'members_of'
        match '/members/:user_id' => 'groups#remove_user', via: :delete, as: 'member_of'
        # this should be put into it's own resource
        match '/memberships/:membership_id' => 'groups#edit_membership', via: :put, as: 'membership_of'
        match '/memberships/:membership_id' => 'groups#destroy_membership', via: :delete
        match '/memberships' => 'groups#create_memberships', via: :post, as: 'memberships_of'
      end
    end

    resources :roles, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        put '/' => 'roles#bulk_update'
        get :report
      end
    end

    resources :auth_sources, :ldap_auth_sources do
      member do
        get :test_connection
      end
    end
  end

  # We should fix this crappy routing (split up and rename controller methods)
  get '/settings' => 'settings#index'
  scope 'settings', controller: 'settings' do
    match 'edit', action: 'edit', via: [:get, :post]
    match 'plugin/:id', action: 'plugin', via: [:get, :post]
  end

  # We should fix this crappy routing (split up and rename controller methods)
  get '/workflows' => 'workflows#index'
  scope 'workflows', controller: 'workflows' do
    match 'edit', action: 'edit', via: [:get, :post]
    match 'copy', action: 'copy', via: [:get, :post]
  end

  namespace :work_packages do
    match 'auto_complete' => 'auto_completes#index', via: [:get, :post]
    resources :calendar, controller: 'calendars', only: [:index]
    resource :bulk, controller: 'bulk', only: [:edit, :update, :destroy]
  end

  resources :work_packages, only: [:show, :edit, :update, :index] do
    get :new_type, on: :member

    get :column_data, on: :collection # TODO move to API

    resources :relations, controller: 'work_package_relations', only: [:create, :destroy]

    # move bulk of wps
    get 'move/new' => 'work_packages/moves#new', on: :collection, as: 'new_move'
    post 'move' => 'work_packages/moves#create', on: :collection, as: 'move'
    # move individual wp
    resource :move, controller: 'work_packages/moves', only: [:new, :create]

    # this duplicate mapping is required for the timelog_helper
    namespace :time_entries do
      resource :report, controller: 'reports'
    end
    resources :time_entries, controller: 'timelog'

    post :preview, on: :collection
    post :preview, on: :member

    get 'quoted/:id', action: 'quoted', on: :collection

    get '/edit' => 'work_packages#edit', on: :member # made explicit to avoid conflict with catch-all route
    # states managed by client-side routing on work_package#index
    get '/*state' => 'work_packages#index', on: :member, id: /\d+/
  end

  resources :versions, only: [:show, :edit, :update, :destroy] do
    member do
      get :status_by
    end
  end

  # Misc journal routes. TODO: move into resources
  match '/journals/:id/diff/:field' => 'journals#diff', via: :get, as: 'journal_diff'

  namespace :time_entries do
    resource :report, controller: 'reports',
                      only: [:show]
  end

  resources :time_entries, controller: 'timelog'

  resources :activity, :activities, only: :index, controller: 'activities'

  resources :users do
    member do
      match '/edit/:tab' => 'users#edit', via: :get
      match '/memberships/:membership_id/destroy' => 'users#destroy_membership', via: :post
      match '/memberships/:membership_id' => 'users#edit_membership', via: :post
      match '/memberships' => 'users#edit_membership', via: :post
      post :change_status
      post :edit_membership
      post :destroy_membership
      get :deletion_info
    end
  end

  resources :boards, only: [] do
    resources :topics, controller: 'messages', except: [:index], shallow: true do
      member do
        get :quote
        post :reply, as: 'reply_to'
        post :preview
      end

      post :preview, on: :collection
    end
  end

  resources :news, only: [:index, :destroy, :update, :edit, :show] do
    resources :comments, controller: 'news/comments', only: [:create, :destroy], shallow: true

    post :preview, on: :member
    post :preview, on: :collection
  end

  resources :attachments, only: [:show, :destroy], format: false do
    member do
      scope via: :get,  constraints: { id: /\d+/, filename: /[^\/]*/ } do
        match 'download(/:filename)' => 'attachments#download', as: 'download'
        match ':filename' => 'attachments#show'
      end
    end
  end
  # redirect for backwards compatibility
  scope constraints: { id: /\d+/, filename: /[^\/]*/ } do
    get '/attachments/download/:id/:filename' => redirect("#{rails_relative_url_root}/attachments/%{id}/download/%{filename}"), format: false
    get '/attachments/download/:id' => redirect("#{rails_relative_url_root}/attachments/%{id}/download"), format: false
  end

  scope controller: 'sys' do

app/models/repository/git.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

require 'open_project/scm/adapters/git'

class Repository::Git < Repository
  attr_protected :root_url
  validates_presence_of :url

  def self.scm_adapter_class
    OpenProject::Scm::Adapters::Git
  end

  def configure(scm_type, _args)
    if scm_type == self.class.managed_type
      unless manageable?
        raise OpenProject::Scm::Exceptions::RepositoryBuildError.new(
          I18n.t('repositories.managed.error_not_manageable')
        )
      end

      self.root_url = managed_repository_path
      self.url = managed_repository_url
    end
  end

  def self.permitted_params(params)
    super(params).merge(params.permit(:path_encoding))
  end

  def self.supported_types
    types = [:local]
    types << managed_type if manageable?

    types
  end

  def managed_repo_created
    scm.initialize_bare_git
  end

  def repository_identifier
    "#{super}.git"
  end

  ##
  # Git doesn't like local urls when visiting
  # the repository, thus always use the path.
  def managed_repository_url
    managed_repository_path
  end

  def supports_directory_revisions?
    true
  end

  def repo_log_encoding
    'UTF-8'
  end

  # Returns the identifier for the given git changeset
  def self.changeset_identifier(changeset)
    changeset.scmid
  end

  # Returns the readable identifier for the given git changeset
  def self.format_changeset_identifier(changeset)
    format_revision(changeset.revision)
  end

  def self.format_revision(revision)
    revision[0, 8]
  end

  def branches
    scm.branches
  end

  def tags
    scm.tags
  end

  def find_changeset_by_name(name)
    return nil if name.nil? || name.empty?
    e = changesets.where(['revision = ?', name.to_s]).first
    return e if e
    changesets.where(['scmid LIKE ?', "#{name}%"]).first
  end

  # With SCM's that have a sequential commit numbering, redmine is able to be
  # clever and only fetch changesets going forward from the most recent one
  # it knows about.  However, with git, you never know if people have merged
  # commits into the middle of the repository history, so we should parse
  # the entire log. Since it's way too slow for large repositories, we only
  # parse 1 week before the last known commit.
  # The repository can still be fully reloaded by calling #clear_changesets
  # before fetching changesets (eg. for offline resync)
  def fetch_changesets
    c = changesets.order('committed_on DESC').first
    since = (c ? c.committed_on - 7.days : nil)

    revisions = scm.revisions('', nil, nil, all: true, since: since, reverse: true)
    return if revisions.nil? || revisions.empty?

    recent_changesets = changesets.where(['committed_on >= ?', since])

    # Clean out revisions that are no longer in git
    recent_changesets.each do |c| c.destroy unless revisions.detect { |r| r.scmid.to_s == c.scmid.to_s } end

    # Subtract revisions that redmine already knows about
    recent_revisions = recent_changesets.map(&:scmid)
    revisions.reject! do |r| recent_revisions.include?(r.scmid) end

    # Save the remaining ones to the database
    unless revisions.nil?
      revisions.each do |rev|
        transaction do
          changeset = Changeset.new(
            repository: self,
            revision:   rev.identifier,
            scmid:      rev.scmid,
            committer:  rev.author,
            committed_on: rev.time,
            comments:   rev.message)

          if changeset.save
            rev.paths.each do |file|
              Change.create(
                changeset: changeset,
                action:    file[:action],
                path:      file[:path])
            end
          end
        end
      end
    end
  end

  def latest_changesets(path, rev, limit = 10)
    revisions = scm.revisions(path, nil, rev, limit: limit, all: false)
    return [] if revisions.nil? || revisions.empty?

    changesets.where(['scmid IN (?)', revisions.map!(&:scmid)])
      .order('committed_on DESC')
  end
end

app/views/repositories/_breadcrumbs.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= link_to 'root', :action => 'show', :project_id => @project, :path => nil, :rev => @rev %>
<%
dirs = path.split('/')
if 'file' == kind
    filename = dirs.pop
end
link_path = ''
dirs.each do |dir|
    next if dir.blank?
    link_path << '/' unless link_path.empty?
    link_path << "#{dir}"
    %>
    &#x00BB; <%= link_to h(dir), :action => 'show', :project_id => @project,
                :path => to_path_param(link_path), :rev => @rev %>
<% end %>
<% if filename %>
    &#x00BB; <%= link_to h(filename),
                   :action => 'changes', :project_id => @project,
                   :path => to_path_param("#{link_path}/#{filename}"), :rev => @rev %>
<% end %>
<%
  # @rev is revsion or git branch or tag.
  rev_text = @changeset.nil? ? @rev : format_revision(@changeset)
%>
<%= "@ #{h rev_text}" unless rev_text.blank? %>

<% html_title(h(with_leading_slash(path))) -%>

app/views/repositories/_dir_list.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<table class="list entries" id="browser">
  <thead>
    <tr id="root">
      <th><%= Attachment.human_attribute_name(:filename) %></th>
      <th><%= Attachment.human_attribute_name(:filesize) %></th>
      <th><%= l(:label_revision) %></th>
      <th><%= l(:label_age) %></th>
      <th><%= Changeset.human_attribute_name(:author) %></th>
      <th><%= Changeset.human_attribute_name(:comments) %></th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'dir_list_content' %>
  </tbody>
</table>

app/views/repositories/_navigation.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'repository_navigation' %>
<% end %>
<% merge ||= {} %>
<%= toolbar title: l(:label_repository) do %>
  <% if User.current.allowed_to?(:browse_repository, @project) %>
  <li class="toolbar-item">
    <%= link_to stats_project_repository_path(@project), class: 'button' do %>
      <i class="button--icon icon-stats1"></i>
      <span class="button--text"><%= l(:label_statistics) %></span>
    <% end %>
  </li>
  <% end %>
  <%= call_hook(:repositories_navigation_toolbar, { repository: @repository, project: @project }) %>
  <% if User.current.allowed_to?(:manage_repository, @project) %>
    <li class="toolbar-item">
      <%= link_to settings_project_path(@project, tab: 'repository') , class: 'button' do %>
        <i class="button--icon icon-settings"></i>
        <span class="button--text"><%= l(:label_settings) %></span>
      <% end %>
    </li>
  <% end %>
<% end %>
<div>
  <h3>
    <%= render :partial => 'breadcrumbs', :locals => { :path => @path, :revision => @rev }.merge(merge) %>
  </h3>
</div>

app/views/repositories/destroy_info.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<%= toolbar title: l(:label_confirmation) %>
<div class="notification-box -warning <%= @repository.managed? ? '-severe' : '' %>">
  <div class="notification-box--content">
    <p><strong><%= l('repositories.destroy.title') %></strong><br /></p>
    <p>
      <% if @repository.managed? %>
        <%= l('repositories.destroy.managed_text', project_name: @project.identifier) %>
        <br/>
        <%= l('repositories.destroy.managed_path_note', path: @repository.root_url) %>
      <% else %>
        <%= simple_format l('repositories.destroy.linked_text',
                          project_name: @project.identifier, url: @repository.url) %>
      <% end %>
    </p>
    <p>
      <%= link_to project_repository_path(@project),
        :method => :delete,
        :class => 'button' do %>
        <i class="button--icon icon-delete"></i>
        <span class="button--text"><%= l(:button_delete) %></span>
      <% end %>
    </p>
  </div>
</div>

app/views/repositories/entry.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= call_hook(:view_repositories_show_contextual, { :repository => @repository, :project => @project }) %>

<%= render :partial => 'navigation', locals: { merge: { kind: 'file'} } %>

<p><%= render :partial => 'link_to_functions' %></p>

<%= render :partial => 'common/file', :locals => {:filename => @path, :content => @content} %>

app/views/repositories/show.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= call_hook(:view_repositories_show_contextual, { :repository => @repository, :project => @project }) %>


<%= render :partial => 'navigation', locals: { merge: { kind: 'dir' } } %>

<% if !@entries.nil? && authorize_for('repositories', 'browse') %>
<%= render :partial => 'dir_list' %>
<% end %>

<%= render_properties(@properties) %>

<%# rev => nil prevents overwriting the rev parameter queried for in the form with the parameter from the request %>
<%= form_tag({ action: controller.action_name,
               project_id: @project,
               path: to_path_param(@path),
               rev: nil
             },
             method: :get,
             id: 'revision_selector',
             class: 'form -vertical'
            ) do %>
<fieldset class="form--fieldset">
  <legend class="form--fieldset-legend"><%= l(:label_revision_plural) %></legend>
  <div class="grid-block wrap">
    <div class="form--column medium-3">
      <div class="form--field -wide-label -break-words ">
        <label class="form--label"><%= l('repositories.go_to_revision') %></label>
        <div class="form--field-container">
          <div class="form--text-field-container">
            <%= text_field_tag :rev, @rev, id: 'revision-identifier-input', placeholder: l(:label_revision) %>
          </div>
        </div>
      </div>
    </div>
    <% if !@repository.branches.nil? && @repository.branches.length > 0 %>
    <div class="form--column medium-3">
      <div class="form--field -wide-label -break-words ">
        <label class="form--label"><%= l(:label_branch) %></label>
        <div class="form--field-container">
          <div class="form--select-container">
            <%= select_tag :branch, options_for_select([''] + @repository.branches, @rev), id: 'revision-branch-select' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% if !@repository.tags.nil? && @repository.tags.length > 0 %>
    <div class="form--column medium-3">
      <div class="form--field -wide-label -break-words ">
        <label class="form--label"><%= l(:label_tag) %></label>
        <div class="form--field-container">
          <div class="form--select-container">
            <%= select_tag :tag, options_for_select([''] + @repository.tags, @rev), id: 'revision-tag-select' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% if User.current.impaired? %>
    <div>
      <%= button_tag 'OK', type: :submit, class: 'button -highlight' %>
    </div>
  <% end %>
</fieldset>
<% end %>
<% if authorize_for('repositories', 'revisions') %>
<%   if @changesets && !@changesets.empty? %>
<%=    render :partial => 'revisions',
              :locals => {:project => @project, :path => @path,
                          :revisions => @changesets, :entry => nil }%>
<%   end %>
<p>
<%
     has_branches = (!@repository.branches.nil? && @repository.branches.length > 0)
     sep = ''
 %>

<%   if @repository.supports_all_revisions? && @path.blank? %>
<%= link_to l(:label_view_all_revisions), revisions_project_repository_path(@project) %>
<%   sep = '|' %>
<%   end %>
<%
     if @repository.supports_directory_revisions? &&
         ( has_branches || !@path.blank? || !@rev.blank? )
 %>
<%= sep %>
<%=
    link_to l(:label_view_revisions),
            :action => 'changes',
            :project_id => @project,
            :path   => to_path_param(@path),
            :rev    => @rev
            %>
<%   end %>
</p>

<%   if true # @path.blank? %>
<%     content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom,
                              params.merge( { :format => 'atom',
                                              :action => 'revisions',
                                              :project_id => @project,
                                              :page => nil,
                                              :key => User.current.rss_key })) %>
<%     end %>

<%= other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:action => 'revisions', :project_id => @project, :key => User.current.rss_key} %>
<%     end %>
<%   end %>
<% end %>

<% html_title(l(:label_repository)) -%>