config/routes.rb
                       }

    namespace :v2 do
      resources :authentication
      resources :users, only: [:index]
      resources :planning_element_journals
      resources :statuses
      resources :colors, controller: 'planning_element_type_colors'
      resources :planning_element_types
      resources :planning_elements
      resources :project_types
      resources :reported_project_statuses
      resources :statuses, only: [:index, :show]
      resources :timelines
      resources :planning_element_priorities, only: [:index]

      resources :projects do
        resources :planning_elements
        resources :planning_element_types
        resources :reportings do
          get :available_projects, on: :collection
        end
        resources :project_associations do
          get :available_projects, on: :collection
        end
        resources :statuses, only: [:index, :show]
        resources :versions, only: [:index]
        resources :users, only: [:index]

        member do
          get :planning_element_custom_fields
        end
        resources :workflows, only: [:index]

        collection do
          get :level_list
        end
      end

      resources :custom_fields

      namespace :pagination, as: 'paginate' do
        [:users,
         :principals,
         :statuses,
         :types,
         :project_types,
         :reported_project_statuses,
         :projects].each do |model|
          resources model, only: [:index]
        end
      end
    end

    namespace :experimental do
      resources :work_packages, only: [:index] do
        get :column_data, on: :collection
        get :column_sums, on: :collection
      end
      resources :queries, only: [:create, :update, :destroy] do
        get :available_columns, on: :collection
        get :custom_field_filters, on: :collection
        get :grouped, on: :collection
      end

      resources :projects, only: [:show, :index] do
        resources :work_packages, only: [:index] do
          get :column_sums, on: :collection
        end
        resources :queries, only: [:create, :update, :destroy] do
          get :available_columns, on: :collection
          get :custom_field_filters, on: :collection
          get :grouped, on: :collection
        end
        resources :versions, only: [:index]
        get :sub_projects
        resources :users, only: [:index]
      end

      resources :versions, only: [:index]
      resources :groups, only: [:index]
      resources :roles, only: [:index]
      resources :users, only: [:index]
    end
  end

  # Because of https://github.com/intridea/grape/pull/853/files this has to be
  # placed behind handling the deprecated v1 because otherwise, a 405 is
  # returned for all routes for which the v3 has also resources. Grape does
  # remove the prefix (v3) before checking whether the method is supported. I
  # don't understand why that should make sense.
  mount API::Root => '/'

  get '/roles/workflow/:id/:role_id/:type_id' => 'roles#workflow'
  get '/help/:ctrl/:page' => 'help#index'

  resources :types do
    post 'move/:id', action: 'move', on: :collection
  end

  resources :statuses, except: :show do
    collection do
      post 'update_work_package_done_ratio'
    end
  end
  resources :custom_fields, except: :show
  get '(projects/:project_id)/search' => 'search#index', as: 'search'

  # only providing routes for journals when there are multiple subclasses of journals
  # all subclasses will look for the journals routes
  resources :journals, only: [:edit, :update] do
    get :preview, on: :member
  end

  # REVIEW: review those wiki routes
  scope 'projects/:project_id/wiki/:id' do
    resource :wiki_menu_item, only: [:edit, :update]
  end

  scope 'projects/:project_id/query/:query_id' do
    resources :query_menu_items, except: [:show]
  end

  get 'projects/:project_id/wiki/new' => 'wiki#new', as: 'wiki_new'
  post 'projects/:project_id/wiki/new' => 'wiki#create', as: 'wiki_create'
  get 'projects/:project_id/wiki/:id/new' => 'wiki#new_child', as: 'wiki_new_child'
  get 'projects/:project_id/wiki/:id/toc' => 'wiki#index', as: 'wiki_page_toc'
  post 'projects/:project_id/wiki/preview' => 'wiki#preview', as: 'preview_wiki'
  post 'projects/:id/wiki' => 'wikis#edit'
  delete 'projects/:id/wiki/destroy' => 'wikis#destroy'

  # generic route for adding/removing watchers.
  # Models declared as acts_as_watchable will be automatically added to
  # OpenProject::Acts::Watchable::Routes.watched
  scope ':object_type/:object_id', constraints: OpenProject::Acts::Watchable::Routes do
    resources :watchers, only: [:new, :create]

    match '/watch' => 'watchers#watch', via: :post
    match '/unwatch' => 'watchers#unwatch', via: :delete
  end

  resources :watchers, only: [:destroy]

  # TODO: remove
  scope 'issues' do
    get 'changes' => 'journals#index', as: 'changes'
  end

  resources :projects, except: [:edit] do
    member do
      # this route let's you access the project specific settings (by tab)
      #
      #   settings_project_path(@project)
      #     => "/projects/1/settings"
      #
      #   settings_project_path(@project, :tab => 'members')
      #     => "/projects/1/settings/members"
      #
      get 'settings(/:tab)', action: 'settings', as: :settings

      match 'copy_project_from_(:coming_from)' => 'copy_projects#copy_project', via: :get, as: :copy_from,
            constraints: { coming_from: /(admin|settings)/ }
      match 'copy' => 'copy_projects#copy', via: :post
      put :modules
      put :archive
      put :unarchive
      patch :types

      get 'column_sums', controller: 'work_packages'

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info, as: 'confirm_destroy'
    end

    resource :enumerations, controller: 'project_enumerations', only: [:update, :destroy]

    resources :versions, only: [:new, :create] do
      collection do
        put :close_completed
      end
    end

    # this is only another name for versions#index
    # For nice "road in the url for the index action
    # this could probably be rewritten with a resource :as => 'roadmap'
    match '/roadmap' => 'versions#index', via: :get

    resources :news, only: [:index, :new, :create]

    namespace :time_entries do
      resource :report, controller: 'reports', only: [:show]
    end
    resources :time_entries, controller: 'timelog'

    resources :wiki, except: [:index, :new, :create] do
      collection do
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/diff/:version/vs/:version_from' => 'wiki#diff', as: 'wiki_diff_compare'
        get '/diff(/:version)' => 'wiki#diff', as: 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', as: 'wiki_annotate'
        match :rename, via: [:get, :patch]
        get :parent_page, action: 'edit_parent_page'
        patch :parent_page, action: 'update_parent_page'
        get :history
        post :protect
        post :add_attachment
        get :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
        post :preview
      end
    end
    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => 'wiki#show'

    namespace :work_packages do
      resources :calendar, controller: 'calendars', only: [:index]
    end

    resources :work_packages, only: [:new, :create] do
      get :new_type, on: :collection

      collection do
        match '/report/:detail' => 'work_packages/reports#report_details', via: :get
        match '/report' => 'work_packages/reports#report', via: :get
      end

      # states managed by client-side routing on work_package#index
      get '/*state' => 'work_packages#index', on: :member, id: /\d+/

      # explicitly define index for preserving the order in which
      # the path helpers are created - this otherwise leads to
      # link_to { controller: ... } to point to the create_new path
      get '/' => 'work_packages#index', on: :collection
      get '/create_new' => 'work_packages#index', on: :collection
    end

    resources :activity, :activities, only: :index, controller: 'activities'

    resources :boards do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, except: [:index, :show], shallow: true

    resources :members, only: [:create, :update, :destroy], shallow: true do
      match :autocomplete_for_member, on: :collection, via: [:get, :post]
    end

    resource :repository, controller: 'repositories', except: [:new] do
      get :edit # needed as show is configured manually with a wildcard

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info
      get :committers
      post :committers
      get :graph
      get :revisions

      get '/statistics', action: :stats, as: 'stats'

      get '(/revisions/:rev)/diff.:format', action: :diff
      get '(/revisions/:rev)/diff(/*path)', action: :diff,
                                            format: false

      get '(/revisions/:rev)/:format/*path', action: :entry,
                                             format: /raw/,
                                             rev: /[a-z0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*path)", format: false,
                                                   action: action,
                                                   rev: /[a-z0-9\.\-_]+/
      end

      get '/revision(/:rev)', rev: /[a-z0-9\.\-_]+/,
                              action: :revision,

app/helpers/search_helper.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

module SearchHelper
  def highlight_tokens(text, tokens)
    return text unless text && tokens && !tokens.empty?
    re_tokens = tokens.map { |t| Regexp.escape(t) }
    regexp = Regexp.new "(#{re_tokens.join('|')})", Regexp::IGNORECASE
    result = ''
    text.split(regexp).each_with_index do |words, i|
      if result.length > 1200
        # maximum length of the preview reached
        result << '...'
        break
      end
      if i.even?
        result << h(words.length > 100 ? "#{words.slice(0..44)} ... #{words.slice(-45..-1)}" : words)
      else
        t = (tokens.index(words.downcase) || 0) % 4
        result << content_tag('span', h(words), class: "highlight token-#{t}")
      end
    end
    result.html_safe
  end

  def highlight_first(texts, tokens)
    texts.each do |text|
      if has_tokens? text, tokens
        return highlight_tokens text, tokens
      end
    end
    highlight_tokens texts[-1], tokens
  end

  def has_tokens?(text, tokens)
    return false unless text && tokens && !tokens.empty?
    re_tokens = tokens.map { |t| Regexp.escape(t) }
    regexp = Regexp.new "(#{re_tokens.join('|')})", Regexp::IGNORECASE
    !!regexp.match(text)
  end

  def last_journal(event)
    if event.respond_to? :last_journal
      event.last_loaded_journal
    end
  end

  def notes_anchor(event)
    version = event.version.to_i

    (version > 1) ? "note-#{version - 1}" : ''
  end

  def with_notes_anchor(event, tokens)
    if has_tokens? last_journal(event).try(:notes), tokens
      event.event_url.merge anchor: notes_anchor(last_journal event)
    else
      event.event_url
    end
  end

  def type_label(t)
    l("label_#{t.singularize}_plural", default: t.to_s.humanize)
  end

  def project_select_tag
    options = [[l(:label_project_all), 'all']]
    options << [l(:label_my_projects), 'my_projects'] unless User.current.memberships.empty?
    options << [l(:label_and_its_subprojects, @project.name), 'subprojects'] unless @project.nil? || @project.descendants.active.empty?
    options << [@project.name, 'current_project'] unless @project.nil?
    styled_select_tag('scope', options_for_select(options, current_scope)) if options.size > 1
  end

  def render_results_by_type(results_by_type)
    links = []
    # Sorts types by results count
    results_by_type.keys.sort { |a, b| results_by_type[b] <=> results_by_type[a] }.each do |t|
      c = results_by_type[t]
      next if c == 0
      text = "#{type_label(t)} (#{c})"
      target = {
        controller: 'search',
        project_id: (@project.identifier if @project),
        action: 'index',
        q: params[:q],
        titles_only: params[:title_only],
        all_words: params[:all_words],
        scope: current_scope,
        t => 1
      }
      links << link_to(h(text), target)
    end
    ('<ul>' + links.map { |link| content_tag('li', link) }.join(' ') + '</ul>').html_safe unless links.empty?
  end

  def current_scope
    params[:scope] || ('current_project' unless @project.nil?)
  end

  def link_to_previous_search_page(pagination_previous_date)
    link_to_content_update(l(:label_previous),
                           params.merge(previous: 1, offset: pagination_previous_date.to_r.to_s), class: 'navigate-left')
  end

  def link_to_next_search_page(pagination_next_date)
    link_to_content_update(l(:label_next),
                           params.merge(previous: nil, offset: pagination_next_date.to_r.to_s), class: 'navigate-right')
  end
end

app/views/search/_mini_form.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<div class="top-menu-search--wrapper">
  <%= label_tag("q", l(:label_search), :class => "hidden-for-sighted") %>

  <%= form_tag(search_path(@project), method: :get) do %>
    <%= hidden_field_tag(controller.default_search_scope, 1, :project_id => nil) if controller.default_search_scope %>

    <expandable-search class="top-menu-search -collapsed" ng-class="{'-collapsed': collapsed === true}">
      <div>
        <%= text_field_tag 'q', @question, :size => 20, :class => 'top-menu-search--input', :placeholder => l(:search_input_placeholder) %>
        <a id="top-menu-search-button"
           class="top-menu-search--button search-form-normal"
           title="<%= l(:label_search) %>"
           accesskey="<%= accesskey(:quick_search) %>" tabindex="0">
           <i class="icon5 icon-search ellipsis"></i>
        </a>
      </div>
    </expandable-search>
  <% end %>
</div>

app/views/search/_pagination.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<div class="search-pagination">
  <p>
    <% if pagination_previous_date %>
      <%= link_to_previous_search_page(pagination_previous_date) %>
    <% end %>
    <% if pagination_next_date %>
      <%= link_to_next_search_page(pagination_next_date) %>
    <% end %>
  </p>
</div>

app/views/search/index.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% content_for :header_tags do %>
  <%= call_hook :search_index_head %>
<% end %>
<%= toolbar title: l(:label_search) %>
<%= styled_form_tag(search_path(@project), :method => :get) do %>
  <fieldset class="simple-filters--container" id="search-filter">
    <ul class="simple-filters--filters">
      <li class="simple-filters--filter">
        <%= styled_label_tag "search-input", l(:description_search), :class => "hidden-for-sighted simple-filters--filter-name" %>
        <div class="simple-filters--filter-value">
          <%= styled_text_field_tag :q, @question, id: 'search-input' %>
        </div>
      </li>
      <li class="simple-filters--filter">
        <%= styled_label_tag :scope, l(:description_project_scope), class: 'hidden-for-sighted simple-filters--filter-name' %>
        <div class="simple-filters--filter-value">
          <%= project_select_tag %>
        </div>
      </li>
      <li class="simple-filters--filter">
        <span class="form--field -trailing-label">
          <%= styled_label_tag :all_words, l(:label_all_words) %>
          <span class="form--field-container">
            <%= styled_check_box_tag 'all_words', 1, @all_words %>
          </span> 
        </span>
        <span class="form--field -trailing-label">
          <%= styled_label_tag :titles_only, l(:label_search_titles_only) %>
          <span class="form--field-container">
            <%= styled_check_box_tag 'titles_only', 1, @titles_only %> 
          </span>
        </span>

      </li>
      <li class="simple-filters--filter">
          <% @object_types.each do |t| %>
            <span class="form--field -trailing-label">
              <%= styled_label_tag t, type_label(t) %>
              <span class="form--field-container">
                <%= styled_check_box_tag t, 1, @scope.include?(t) %> 
              </span>
            </span>
          <% end %>
      </li>
    </ul>
    <%= styled_submit_tag l(:button_submit), :name => 'submit', class: 'button -highlight -small' %>
  </fieldset>
<% end %>
<% if @results %>
  <div id="search-results-counts">
    <%= render_results_by_type(@results_by_type) unless @scope.size == 1 %>
  </div>
  <h3><%= l(:label_result_plural) %> (<%= @results_by_type.values.sum %>)</h3>
  <%= render :partial => 'pagination', :locals => {:pagination_previous_date => @pagination_previous_date, :pagination_next_date => @pagination_next_date } %>
  <dl id="search-results">
    <% @results.each do |e| %>
      <dt class="<%= e.event_type %>">
        <%= icon_wrapper("icon-context icon-#{e.event_type}", e.event_name) %>
        <% if e.project != @project %>
          <span class="project"><%= e.project %></span>
        <% end %>
        <%= link_to highlight_tokens(truncate(e.event_title, :length => 255), @tokens), with_notes_anchor(e, @tokens) %>
      </dt>
      <dd><span class="description"><%= highlight_first([last_journal(e).try(:notes), e.event_description], @tokens) %></span>
        <span class="author"><%= format_time(e.event_datetime) %></span></dd>
    <% end %>
  </dl>
<% end %>
<%= render :partial => 'pagination', :locals => {:pagination_previous_date => @pagination_previous_date, :pagination_next_date => @pagination_next_date } %>
<% html_title(l(:label_search)) -%>