config/routes.rb
  # Redirect wp short url for work packages to full URL
  get '/wp(/)'    => redirect("#{rails_relative_url_root}/work_packages")
  get '/wp/*rest' => redirect { |params, _req| "#{rails_relative_url_root}/work_packages/#{URI.escape(params[:rest])}" }

  scope controller: 'account' do
    get '/account/force_password_change', action: 'force_password_change'
    post '/account/change_password', action: 'change_password'
    match '/account/lost_password', action: 'lost_password', via: [:get, :post]
    match '/account/register', action: 'register', via: [:get, :post]

    # omniauth routes
    match '/auth/:provider/callback', action: 'omniauth_login',
                                      as: 'omniauth_login',
                                      via: [:get, :post]
    get '/auth/failure', action: 'omniauth_failure'

    match '/login', action: 'login',  as: 'signin', via: [:get, :post]
    get '/logout', action: 'logout', as: 'signout'
  end

  namespace :api do
    # Handles all routes of the now removed api v1.
    # Always returns a 410.
    # This does not care if the route actually existed to
    # avoid maintaining knowledge of the now removed api.
    match '/v1/*rest', via: [:get, :post, :put, :delete],
                       to: proc {
                         [410,
                          { 'Content-Type' => 'text/plain' },
                          ["OpenProject API v1 has been removed.\n" \
                           'See https://community.openproject.org/news/65']]
                       }

    namespace :v2 do
      resources :authentication
      resources :users, only: [:index]
      resources :planning_element_journals
      resources :statuses
      resources :colors, controller: 'planning_element_type_colors'
      resources :planning_element_types
      resources :planning_elements
      resources :project_types
      resources :reported_project_statuses
      resources :statuses, only: [:index, :show]
      resources :timelines
      resources :planning_element_priorities, only: [:index]

      resources :projects do
        resources :planning_elements
        resources :planning_element_types
        resources :reportings do
          get :available_projects, on: :collection
        end
        resources :project_associations do
          get :available_projects, on: :collection
        end
        resources :statuses, only: [:index, :show]
        resources :versions, only: [:index]
        resources :users, only: [:index]

        member do
          get :planning_element_custom_fields
        end
        resources :workflows, only: [:index]

        collection do
          get :level_list
        end
      end

      resources :custom_fields

      namespace :pagination, as: 'paginate' do
        [:users,
         :principals,
         :statuses,
         :types,
         :project_types,
         :reported_project_statuses,
         :projects].each do |model|
          resources model, only: [:index]
        end
      end
    end

    namespace :experimental do
      resources :work_packages, only: [:index] do
        get :column_data, on: :collection
        get :column_sums, on: :collection
      end
      resources :queries, only: [:create, :update, :destroy] do
        get :available_columns, on: :collection
        get :custom_field_filters, on: :collection
        get :grouped, on: :collection
      end

      resources :projects, only: [:show, :index] do
        resources :work_packages, only: [:index] do
          get :column_sums, on: :collection
        end
        resources :queries, only: [:create, :update, :destroy] do
          get :available_columns, on: :collection
          get :custom_field_filters, on: :collection
          get :grouped, on: :collection
        end
        resources :versions, only: [:index]
        get :sub_projects
        resources :users, only: [:index]
      end

      resources :versions, only: [:index]
      resources :groups, only: [:index]
      resources :roles, only: [:index]
      resources :users, only: [:index]
    end
  end

  # Because of https://github.com/intridea/grape/pull/853/files this has to be
  # placed behind handling the deprecated v1 because otherwise, a 405 is
  # returned for all routes for which the v3 has also resources. Grape does
  # remove the prefix (v3) before checking whether the method is supported. I
  # don't understand why that should make sense.
  mount API::Root => '/'

  get '/roles/workflow/:id/:role_id/:type_id' => 'roles#workflow'
  get '/help/:ctrl/:page' => 'help#index'

  resources :types do
    post 'move/:id', action: 'move', on: :collection
  end

  resources :statuses, except: :show do
    collection do
      post 'update_work_package_done_ratio'
    end
  end
  resources :custom_fields, except: :show
  get '(projects/:project_id)/search' => 'search#index', as: 'search'

  # only providing routes for journals when there are multiple subclasses of journals
  # all subclasses will look for the journals routes
  resources :journals, only: [:edit, :update] do
    get :preview, on: :member
  end

  # REVIEW: review those wiki routes
  scope 'projects/:project_id/wiki/:id' do
    resource :wiki_menu_item, only: [:edit, :update]
  end

  scope 'projects/:project_id/query/:query_id' do
    resources :query_menu_items, except: [:show]
  end

  get 'projects/:project_id/wiki/new' => 'wiki#new', as: 'wiki_new'
  post 'projects/:project_id/wiki/new' => 'wiki#create', as: 'wiki_create'
  get 'projects/:project_id/wiki/:id/new' => 'wiki#new_child', as: 'wiki_new_child'
  get 'projects/:project_id/wiki/:id/toc' => 'wiki#index', as: 'wiki_page_toc'
  post 'projects/:project_id/wiki/preview' => 'wiki#preview', as: 'preview_wiki'
  post 'projects/:id/wiki' => 'wikis#edit'
  delete 'projects/:id/wiki/destroy' => 'wikis#destroy'

  # generic route for adding/removing watchers.
  # Models declared as acts_as_watchable will be automatically added to
  # OpenProject::Acts::Watchable::Routes.watched
  scope ':object_type/:object_id', constraints: OpenProject::Acts::Watchable::Routes do
    resources :watchers, only: [:new, :create]

    match '/watch' => 'watchers#watch', via: :post
    match '/unwatch' => 'watchers#unwatch', via: :delete
  end

  resources :watchers, only: [:destroy]

  # TODO: remove
  scope 'issues' do
    get 'changes' => 'journals#index', as: 'changes'
  end

  resources :projects, except: [:edit] do
    member do
      # this route let's you access the project specific settings (by tab)
      #
      #   settings_project_path(@project)
      #     => "/projects/1/settings"
      #
      #   settings_project_path(@project, :tab => 'members')
      #     => "/projects/1/settings/members"
      #
      get 'settings(/:tab)', action: 'settings', as: :settings

      match 'copy_project_from_(:coming_from)' => 'copy_projects#copy_project', via: :get, as: :copy_from,
            constraints: { coming_from: /(admin|settings)/ }
      match 'copy' => 'copy_projects#copy', via: :post
      put :modules
      put :archive
      put :unarchive
      patch :types

      get 'column_sums', controller: 'work_packages'

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info, as: 'confirm_destroy'
    end

    resource :enumerations, controller: 'project_enumerations', only: [:update, :destroy]

    resources :versions, only: [:new, :create] do
      collection do
        put :close_completed
      end
    end

    # this is only another name for versions#index
    # For nice "road in the url for the index action
    # this could probably be rewritten with a resource :as => 'roadmap'
    match '/roadmap' => 'versions#index', via: :get

    resources :news, only: [:index, :new, :create]

    namespace :time_entries do
      resource :report, controller: 'reports', only: [:show]
    end
    resources :time_entries, controller: 'timelog'

    resources :wiki, except: [:index, :new, :create] do
      collection do
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/diff/:version/vs/:version_from' => 'wiki#diff', as: 'wiki_diff_compare'
        get '/diff(/:version)' => 'wiki#diff', as: 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', as: 'wiki_annotate'
        match :rename, via: [:get, :patch]
        get :parent_page, action: 'edit_parent_page'
        patch :parent_page, action: 'update_parent_page'
        get :history
        post :protect
        post :add_attachment
        get :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
        post :preview
      end
    end
    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => 'wiki#show'

    namespace :work_packages do
      resources :calendar, controller: 'calendars', only: [:index]
    end

    resources :work_packages, only: [:new, :create] do
      get :new_type, on: :collection

      collection do
        match '/report/:detail' => 'work_packages/reports#report_details', via: :get
        match '/report' => 'work_packages/reports#report', via: :get
      end

      # states managed by client-side routing on work_package#index
      get '/*state' => 'work_packages#index', on: :member, id: /\d+/

      # explicitly define index for preserving the order in which
      # the path helpers are created - this otherwise leads to
      # link_to { controller: ... } to point to the create_new path
      get '/' => 'work_packages#index', on: :collection
      get '/create_new' => 'work_packages#index', on: :collection
    end

    resources :activity, :activities, only: :index, controller: 'activities'

    resources :boards do

app/models/group.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class Group < Principal
  include ActiveModel::ForbiddenAttributesProtection

  has_and_belongs_to_many :users,
                          join_table:   "#{table_name_prefix}group_users#{table_name_suffix}",
                          after_add:    :user_added,
                          after_remove: :user_removed

  acts_as_customizable

  before_destroy :remove_references_before_destroy

  alias_attribute(:groupname, :lastname)
  validates_presence_of :groupname
  validate :uniqueness_of_groupname
  validates_length_of :groupname, maximum: 30

  def to_s
    lastname.to_s
  end

  alias :name :to_s

  def user_added(user)
    members.each do |member|
      next if member.project.nil?

      user_member = Member.find_by(project_id: member.project_id, user_id: user.id)

      if user_member.nil?
        user_member = Member.new.tap do |m|
          m.project_id = member.project_id
          m.user_id = user.id
        end

        member.member_roles.each do |member_role|
          user_member.add_role(member_role.role, member_role.id)
        end

        user_member.save!
      else
        member.member_roles.each do |member_role|
          user_member.add_and_save_role(member_role.role, member_role.id)
        end
      end
    end
  end

  def user_removed(user)
    members.each do |member|
      MemberRole.includes(:member)
        .where(["#{Member.table_name}.user_id = ? AND #{MemberRole.table_name}.inherited_from IN (?)",
                user.id, member.member_role_ids])
        .references(:members).each do |member_role|
        member_role.member.remove_member_role_and_destroy_member_if_last(member_role)
      end
    end
  end

  # adds group members
  # meaning users that are members of the group
  def add_member!(users)
    self.users << users
  end

  private

  # Removes references that are not handled by associations
  def remove_references_before_destroy
    return if id.nil?

    deleted_user = DeletedUser.first

    WorkPackage.where(assigned_to_id: id).update_all(assigned_to_id: deleted_user.id)

    Journal::WorkPackageJournal.where(assigned_to_id: id)
      .update_all(assigned_to_id: deleted_user.id)
  end

  def uniqueness_of_groupname
    groups_with_name = Group.where('lastname = ? AND id <> ?', groupname, id ? id : 0).count
    if groups_with_name > 0
      errors.add :groupname, :taken
    end
  end
end

app/controllers/api/experimental/groups_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

module Api
  module Experimental
    class GroupsController < ApplicationController
      include ::Api::Experimental::ApiController

      before_filter :authorize_global

      def index
        @groups = Group.all

        respond_to do |format|
          format.api
        end
      end
    end
  end
end

app/helpers/groups_helper.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

module GroupsHelper
  def group_settings_tabs
    [{ name: 'general', partial: 'groups/general', label: :label_general },
     { name: 'users', partial: 'groups/users', label: :label_user_plural },
     { name: 'memberships', partial: 'groups/memberships', label: :label_project_plural }
    ]
  end
end

app/views/groups/_form.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%#
  needs locals:
  :f => labelled form builder
%>

<%= error_messages_for :group %>

<section class="form--section">
  <div class="form--field">
    <%= f.text_field :lastname, :label => Group.human_attribute_name(:name), :required => true %>
  </div>

  <%= render partial: 'customizable/form', locals: { form: f } %>
</section>

app/views/groups/_general.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= labelled_tabular_form_for @group, :url => group_path(@group), :html => {:method => :put}, :as => :group do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= styled_button_tag l(:button_save), class: '-highlight -with-icon icon-yes' %>
<% end %>

app/views/groups/_users.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<div class="grid-block">
  <div class="grid-content">
    <% if @group.users.any? %>
      <table class="list users">
        <thead>
          <tr>
            <th><%= User.model_name.human %></th>
            <th style="width:15%"></th>
          </tr>
        </thead>
        <tbody>
          <% @group.users.sort.each do |user| %>
            <tr id="user-<%= user.id %>" class="<%= cycle 'odd', 'even' %>">
              <td class="user"><%= link_to_user user %></td>
              <td class="buttons">
                <%= link_to l(:button_delete), member_of_group_path(@group, user),
                                           :method => :delete,
                                           :remote => :true,
                                           :class => 'icon icon-delete' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="nodata"><%= l(:label_no_data) %></p>
    <% end %>
  </div>
  <div class="grid-content">
    <% users = User.active.not_in_group(@group).limit(100) %>
    <% if users.any? %>
      <%= styled_form_tag(members_of_group_path(@group), :method => :post, :remote => true) do |f| %>
        <fieldset class="form--fieldset">
          <legend class="form--fieldset-legend"><%=l(:label_user_new)%></legend>
          <div class="form--field -vertical">
            <%= styled_label_tag "user_search", l(:label_user_search) %>
            <div class="form--field-container">
              <%= styled_text_field_tag 'user_search', nil %>
            </div>
          </div>
          <div class="form--field -vertical">
            <%= observe_field(:user_search,
                          :frequency => 0.5,
                          :update => :users,
                          :url => { :controller => '/groups', :action => 'autocomplete_for_user', :id => @group },
                          :with => 'q',
                          :method => :get)
                      %>
            <div id="users" class="form--field-container -vertical">
              <%= principals_check_box_tags 'user_ids[]', users %>
            </div>
          </div>
          <div><%= styled_button_tag l(:button_add), class: '-highlight -with-icon icon-yes' %></div>
        </fieldset>
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/autocomplete_for_user.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= principals_check_box_tags 'user_ids[]', @users %>

app/views/groups/edit.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% html_title l(:label_administration), "#{l(:label_edit)} #{Group.model_name.human} #{h @group.name}" %>
<%= toolbar title: "#{link_to l(:label_group_plural), groups_path} &raquo; #{@group.name}" %>
<%= render_tabs group_settings_tabs %>

app/views/groups/index.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% html_title l(:label_administration), l("label_group_plural") %>
<%= toolbar title: l(:label_group_plural) do %>
  <li class="toolbar-item">
    <%= link_to new_group_path, class: 'button -alt-highlight' do %>
      <i class="button--icon icon-add"></i>
      <span class="button--text"><%= l(:label_group_new) %></span>
    <% end %>
  </li>
<% end %>
<% if @groups.any? %>
  <table class="list groups">
    <thead>
      <tr>
        <th><%= Group.model_name.human %></th>
        <th><%=l(:label_user_plural)%></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= link_to h(group), :action => 'edit', :id => group %></td>
          <td align="center"><%= group.users.size %></td>
          <td class="buttons"><%= link_to l(:button_delete), group, data: { confirm: l(:text_are_you_sure) }, :method => :delete, :class => 'icon icon-delete' %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>

app/views/groups/new.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% html_title l(:label_administration), l("label_group_new") %>
<%= toolbar title: "#{link_to l(:label_group_plural), groups_path} &raquo; #{l(:label_group_new)}" %>

<%= labelled_tabular_form_for(@group) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div><%= f.button l(:button_create), class: 'button -highlight -with-icon icon-yes' %></div>
<% end %>

app/views/groups/show.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2015 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<%= toolbar title: "#{link_to l(:label_group_plural), groups_path} &raquo; #{h @group.name}" %>
<ul>
  <% @group.users.each do |user| %>
    <li><%=h user %></li>
  <% end %>
</ul>